export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";

export const METRIC_TOGGLE_FETCH = 'METRIC_TOGGLE_FETCH';
export const METRIC_SET_CATEGORIES = 'METRIC_SET_CATEGORIES';
