export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";

export const METRIC_TOGGLE = 'METRIC_TOGGLE';
export const METRIC_DATA_RECEIVED = 'METRIC_DATA_RECEIVED';

export const CHART_ADD_DATA = 'CHART_ADD_DATA';
export const CHART_REMOVE_DATA = 'CHART_REMOVE_DATA';